apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceAccount.yaml
  - clusterRole.yaml
  - role.yaml
  - clusterRoleBinding.yaml
  - roleBinding.yaml
  - deployment.yaml

images:
  - name: us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler
    newTag: v1.16.5